# Generated by Django 5.0.1 on 2024-01-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Presupuesto', models.CharField(max_length=150)),
                ('Unidad', models.CharField(max_length=150)),
                ('Tipo', models.CharField(max_length=150)),
                ('Cantidad', models.PositiveIntegerField()),
                ('ValorUnitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ValorTotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('FechaAdquisicion', models.DateField()),
                ('Proveedor', models.CharField(max_length=500)),
                ('Documentacion', models.CharField(max_length=500)),
            ],
        ),
    ]
