# Generated by Django 5.0.1 on 2024-01-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='id',
        ),
        migrations.AddField(
            model_name='registro',
            name='idRegistro',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
