# Generated by Django 5.0.1 on 2024-01-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_remove_registro_idregistro_registro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='id',
        ),
        migrations.AddField(
            model_name='registro',
            name='idRegistro',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
