# Generated by Django 5.0.1 on 2024-01-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0006_remove_registro_id_registro_idregistro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='idRegistro',
        ),
        migrations.AddField(
            model_name='registro',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
