# Generated by Django 5.0.1 on 2024-02-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0011_alter_registro_presupuesto_alter_registro_valortotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Presupuesto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ValorTotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
